#!/usr/bin/env python3
"""Regenerate Sources/PrivMask/Detection/JapaneseSurnames.swift from SudachiDict.

The surname list verifies what the on-device language model returns. A family
name missing from it is a name the model found and we discarded, so the list
wants to be as complete as the precision of a prefix match allows. See #22.

    python3 Scripts/generate-surnames.py

Downloads the pinned SudachiDict release, keeps the rows tagged
名詞,固有名詞,人名,姓 that are written in two or three kanji, and writes the Swift
file. Nothing else in that file is hand-edited; edit this script instead.
"""

from __future__ import annotations

import csv
import io
import sys
import urllib.request
import zipfile
from pathlib import Path

# Pinned so that regenerating twice gives the same file. Raise it deliberately.
RELEASE = "20260723"
URL = f"http://sudachi.s3-website-ap-northeast-1.amazonaws.com/sudachidict-raw/{RELEASE}/small_lex.zip"

OUTPUT = Path(__file__).resolve().parent.parent / "Sources/PrivMask/Detection/JapaneseSurnames.swift"

# Matched as a prefix, so a single-kanji entry admits every word that starts with
# it: SudachiDict knows 533 of them, and with them one common noun in five
# reaches the gate. These are the exception, carried over from the hand-written
# list that preceded this script, and they are not regenerated. 南/原/堀/林/森/金/
# 関/高 are common enough to be worth what they cost; the rest are the Chinese and
# Korean family names common among residents of Japan, which the model does return.
SINGLE_CHARACTER = [
    "南", "原", "堀", "林", "森", "金", "関", "高",
    "李", "劉", "呉", "姜", "孫", "尹", "崔", "張",
    "徐", "朴", "楊", "沈", "王", "趙", "郭", "鄭",
    "陳", "黄",
]

# 々 repeats the previous kanji (佐々木), 〆 and ヶ appear inside a few names.
ITERATION_MARKS = {"々", "〆", "ヶ"}


def is_kanji(text: str) -> bool:
    """True when every character is a kanji or an iteration mark, and at least
    one is a kanji — so that 々 alone, or a stray mark, is not taken for a name."""
    def kanji_scalar(character: str) -> bool:
        code = ord(character)
        return (
            0x4E00 <= code <= 0x9FFF
            or 0x3400 <= code <= 0x4DBF
            or 0xF900 <= code <= 0xFAFF
        )

    if not text:
        return False
    if not all(kanji_scalar(c) or c in ITERATION_MARKS for c in text):
        return False
    return any(kanji_scalar(c) for c in text)


def is_katakana(text: str) -> bool:
    return bool(text) and all(0x30A0 <= ord(c) <= 0x30FF for c in text)


def fetch_lexicon() -> str:
    sys.stderr.write(f"downloading {URL}\n")
    with urllib.request.urlopen(URL) as response:
        payload = response.read()
    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        name = next(n for n in archive.namelist() if n.endswith("small_lex.csv"))
        return archive.read(name).decode("utf-8")


def extract(lexicon: str) -> tuple[list[str], list[str]]:
    """Family names of two or three kanji, and their katakana readings.

    Three characters is a cap rather than an observation: SudachiDict's longest
    family name is five (勅使河原, 正親町三条), and `beginsWithSurname` only ever
    tries prefixes of three, two and one. The 37 entries of four or more are also
    the noisiest part of the tag — 紀伊国屋, 隠岐之島, 酒鬼薔薇 are not people.
    Raising the cap means raising that loop bound too.
    """
    kanji: set[str] = set()
    readings: set[str] = set()
    for row in csv.reader(io.StringIO(lexicon)):
        if len(row) < 12:
            continue
        surface, pos, reading = row[0], row[5:9], row[11]
        if pos != ["名詞", "固有名詞", "人名", "姓"]:
            continue
        if not is_kanji(surface) or not 2 <= len(surface) <= 3:
            continue
        kanji.add(surface)
        # Every reading, not one per spelling. 中田 is ナカタ or ナカダ and 河野 is
        # カワノ or コウノ; keeping only the first loses 523 readings, and whoever
        # has the other one writes their name in katakana and goes unmasked.
        if is_katakana(reading):
            readings.add(reading)

    return sorted(kanji), sorted(readings)


def wrap(entries: list[str], width: int = 88) -> str:
    """One long literal rather than a Set literal: the Swift type checker takes
    minutes over a collection literal this size, and seconds over a string."""
    lines: list[str] = []
    current = ""
    for entry in entries:
        candidate = entry if not current else f"{current} {entry}"
        if len(candidate) > width:
            lines.append(current)
            current = entry
        else:
            current = candidate
    if current:
        lines.append(current)
    return "\n".join(f"        {line}" for line in lines)


TEMPLATE = '''import Foundation

// Generated by Scripts/generate-surnames.py from SudachiDict {release}. Do not
// edit the lists by hand; edit the script and run it again.
//
// SudachiDict is Copyright (c) Works Applications Co., Ltd. and is licensed
// under the Apache License, Version 2.0. Its small_lex.csv contains a part of
// UniDic, Copyright (c) 2011-2013 The UniDic Consortium, under a 3-clause BSD
// licence. See https://github.com/WorksApplications/SudachiDict.

/// Japanese family names, used to *verify* candidates the language model
/// returns — never to detect them.
///
/// The distinction matters. As a detector this list would only ever find names
/// somebody already thought of, which is the weakness the model exists to fix.
/// As a check on the model's output it rejects the words the model reaches for
/// when a text contains no names at all: `緊急連絡先`, `全角表記` and `内線` do
/// not begin with a family name, and `サポート窓口` is not even written the way a
/// name is written.
///
/// The list used to hold 188 names chosen by hand, and that was measurably too
/// few: the model returned ten ordinary names — 滝口, 尾形, 井出, 深谷, 市村,
/// 谷村, 玉置, 久田, 畑山, 福士 — and every one was rejected here, leaving the
/// text unmasked. Completeness costs almost nothing at this length: over the
/// 73,030 kanji common nouns in SudachiDict, growing the list from 188 entries
/// to {count:,} moves the share that passes this check from 1.45% to 1.67%. See #22.
public enum JapaneseSurnames {{
    /// Kanji family names.
    public static let kanji: Set<String> = tokenise(multiCharacter).union(tokenise(singleCharacter))

    /// Katakana readings, for names written in katakana rather than kanji.
    public static let katakana: Set<String> = tokenise(katakanaReadings)

    /// True when `text` begins with a family name from either list.
    ///
    /// Kanji family names are one to three characters, so only those prefixes
    /// are tried. Katakana names are matched on their first whitespace-separated
    /// token, since a katakana full name is usually written 「ヤマダ タロウ」 —
    /// matching those by prefix would take ハヤシ out of ハヤシライス.
    public static func beginsWithSurname(_ text: String) -> Bool {{
        let trimmed = text.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty else {{ return false }}

        for length in stride(from: min(3, trimmed.count), through: 1, by: -1) {{
            let prefix = String(trimmed.prefix(length))
            if kanji.contains(prefix) {{ return true }}
        }}

        let firstToken = trimmed.split(separator: " ", maxSplits: 1).first.map(String.init) ?? trimmed
        return katakana.contains(firstToken) || katakana.contains(trimmed)
    }}

    private static func tokenise(_ list: String) -> Set<String> {{
        Set(list.split(whereSeparator: \\.isWhitespace).map(String.init))
    }}

    /// Single-kanji family names, kept by hand rather than generated.
    ///
    /// The check above matches a prefix, so a single-kanji entry admits every
    /// word beginning with it. SudachiDict records 533 of them, and taking them
    /// all would put one common noun in five through this check — 東京都, 西日本,
    /// 新機能, 前提, 今回, 北海道, 所属, 見積書. That is the whole of the precision
    /// cost the length of this list is sometimes blamed for, which is why the
    /// generated part below starts at two characters.
    ///
    /// These are the exception. 南, 原, 堀, 林, 森, 金, 関 and 高 are common
    /// enough to be worth what they cost; the rest are family names common among
    /// Chinese and Korean residents of Japan, which the model does return.
    private static let singleCharacter = "{single}"

    /// Family names of two or three kanji.
    ///
    /// One long literal rather than a `Set` literal: the Swift type checker takes
    /// minutes over a collection literal this size and milliseconds over a string.
    private static let multiCharacter = """
{kanji}
        """

    private static let katakanaReadings = """
{katakana}
        """
}}
'''


def main() -> None:
    kanji, katakana = extract(fetch_lexicon())
    sys.stderr.write(f"{len(kanji)} kanji family names, {len(katakana)} katakana readings\n")

    OUTPUT.write_text(
        TEMPLATE.format(
            release=RELEASE,
            count=len(kanji) + len(SINGLE_CHARACTER),
            single=" ".join(SINGLE_CHARACTER),
            kanji=wrap(kanji),
            katakana=wrap(katakana),
        ),
        encoding="utf-8",
    )
    sys.stderr.write(f"wrote {OUTPUT}\n")


if __name__ == "__main__":
    main()
